### ISSUE TITLE
No effect after applying patch

### ISSUE THREAD

**Issue by Elionna** [oocyberkevinoo/IPSwitch-MegaMix-Patches#10]
I'm attempting to do the force english patch and I have the appropriate files in the rom_switch_en folder but there is no change in the game, any idea what could be going wrong? This is for MEGA39 1.0.5 version.

**Comment by oocyberkevinoo** [comment]
Have you applied patch after selecting it in IPSwitch homebrew ?
Does any other patch is working ?

**Comment by Elionna** [comment]
I have, other patches like the saturation & hachihachi patch, and the watermark removal patch are working, it's just the english one that isn't activating.

**Comment by oocyberkevinoo** [comment]
Hmm.. Axctually I'm using it right now, and it's working, are you 100% sure you enabled the english patch in IPSwitch, and you have all needed files ?

Here the englih patch : https://www.mediafire.com/folder/g66lqyjxolif5/English_Mod

**Comment by oocyberkevinoo** [comment]
I'll consider this one close.
